const scale10=['Nada','Muy bajo','Bajo','Algo bajo','Medio-bajo','Medio','Medio-alto','Alto','Muy alto','Totalmente'];
const zodiac=[['Capricornio',1222,119,'♑'],['Acuario',120,218,'♒'],['Piscis',219,320,'♓'],['Aries',321,419,'♈'],['Tauro',420,520,'♉'],['Géminis',521,620,'♊'],['Cáncer',621,722,'♋'],['Leo',723,822,'♌'],['Virgo',823,922,'♍'],['Libra',923,1022,'♎'],['Escorpio',1023,1121,'♏'],['Sagitario',1122,1221,'♐']];
const affinity={Aries:['Leo','Sagitario','Géminis'],Tauro:['Virgo','Capricornio','Cáncer'],'Géminis':['Libra','Acuario','Aries'],'Cáncer':['Escorpio','Piscis','Tauro'],Leo:['Aries','Sagitario','Libra'],Virgo:['Tauro','Capricornio','Cáncer'],Libra:['Géminis','Acuario','Leo'],Escorpio:['Cáncer','Piscis','Virgo'],Sagitario:['Aries','Leo','Acuario'],Capricornio:['Tauro','Virgo','Escorpio'],Acuario:['Géminis','Libra','Sagitario'],Piscis:['Cáncer','Escorpio','Capricornio']};
const Q={amistad:['¿Qué tan social eres?','¿Cuánto valoras una rutina estable?','¿Qué tanto disfrutas nuevas experiencias?','¿Cuánto tiempo semanal dedicas a amistades?','¿Qué tan importante es compartir sentido del humor?','¿Qué tan importante es la lealtad para ti?'],pareja:['¿Qué tan social eres?','¿Cuánto valoras una rutina estable?','¿Qué tanto disfrutas nuevas experiencias?','¿Qué tan importante es mostrar afecto diario?','¿Qué tan importante es planear proyectos de vida en común?','¿Qué tanto valoras la comunicación emocional profunda?'],trabajo:['¿Qué tan social eres?','¿Cuánto valoras una rutina estable?','¿Qué tanto disfrutas nuevas experiencias?','¿Qué tan cómodo te sientes liderando equipos?','¿Qué tanto prefieres procesos definidos?','¿Qué tan orientado estás a resultados medibles?']};
const state={A:init(),B:init()}; function init(){return {nombre:'',sexo:'hombre',busca:'ambos',vinculo:'amistad',nacionalidad:'',dia:1,mes:1,anio:1998,answers:{}}}
function signo(m,d){const v=m*100+d;for(const [n,s,e,i] of zodiac){if(s<=e&&v>=s&&v<=e)return [n,i];if(s>e&&(v>=s||v<=e))return [n,i]}return ['Aries','♈']}
function zscore(a,b){if(a===b)return 1;return (affinity[a]||[]).includes(b)?.85:.55}
function render(id,key){const p=state[key];const root=document.getElementById(id);const qs=Q[p.vinculo];root.innerHTML=`<h2>Persona ${key}</h2>
<div class="grid"><div><label>Nombre</label><input data-f="nombre" value="${p.nombre}"></div><div><label>Nacionalidad</label><input data-f="nacionalidad" value="${p.nacionalidad}"></div></div>
<div class="grid"><div><label>Sexo</label>${chips(key,'sexo',['hombre','mujer','otro'])}</div><div><label>Busca</label>${chips(key,'busca',['hombre','mujer','ambos'])}</div></div>
<div><label>Tipo de vínculo</label>${chips(key,'vinculo',['amistad','pareja','trabajo'])}</div>
<div class="grid"><div><label>Día</label><input type="number" min="1" max="31" data-f="dia" value="${p.dia}"></div><div><label>Mes</label><input type="number" min="1" max="12" data-f="mes" value="${p.mes}"></div></div>
<div><label>Año</label><input type="number" min="1940" max="${new Date().getFullYear()}" data-f="anio" value="${p.anio}"></div>
<small>Signo: ${signo(p.mes,p.dia)[1]} ${signo(p.mes,p.dia)[0]}</small>
${qs.map((q,qi)=>`<div class="question"><label>${q}</label><div class="question-options">${scale10.map((o,i)=>`<button class="chip ${(p.answers[qi]===i)?'active':''}" data-q="${qi}" data-v="${i}">${i+1}. ${o}</button>`).join('')}</div></div>`).join('')}`;
root.querySelectorAll('input').forEach(i=>i.addEventListener('input',e=>{const f=e.target.dataset.f;state[key][f]=['dia','mes','anio'].includes(f)?Number(e.target.value):e.target.value;calc();renderAll();}));
root.querySelectorAll('button[data-k]').forEach(b=>b.onclick=()=>{state[key][b.dataset.k]=b.dataset.v;state[key].answers={};calc();renderAll();});
root.querySelectorAll('button[data-q]').forEach(b=>b.onclick=()=>{state[key].answers[b.dataset.q]=Number(b.dataset.v);calc();renderAll();});
}
function chips(k,f,arr){return `<div class='row'>${arr.map(v=>`<button data-k='${f}' data-v='${v}' class='chip ${state[k][f]===v?'active':''}'>${v}</button>`).join('')}</div>`}
function calc(){const a=state.A,b=state.B;const [sa]=signo(a.mes,a.dia),[sb]=signo(b.mes,b.dia);const ids=Object.keys(a.answers).filter(k=>k in b.answers);const pref=ids.length?ids.reduce((t,k)=>t+(1-Math.abs(a.answers[k]-b.answers[k])/9),0)/ids.length:0;const z=zscore(sa,sb);const intent=a.vinculo===b.vinculo?(((a.busca==='ambos'||a.busca===b.sexo)&&(b.busca==='ambos'||b.busca===a.sexo))?1:.65):.3;const nat=(a.nacionalidad||'').trim().toLowerCase()===(b.nacionalidad||'').trim().toLowerCase()?1:.75;const score=Math.round((z*.2+pref*.5+intent*.2+nat*.1)*100);document.getElementById('score').textContent=score+'%';document.getElementById('details').textContent=`Zodiaco ${Math.round(z*100)}% · Preferencias ${Math.round(pref*100)}% · Intención ${Math.round(intent*100)}% · Nacionalidad ${Math.round(nat*100)}%`;}
function renderAll(){render('personaA','A');render('personaB','B');}
renderAll();calc();
